name: Build and deploy Eggass

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PRODUCTION: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Compile Rust
      run: |
        wasm-pack build --release
    
    - name: Install NPM packages
      run: |
        cd www
          npm install
        cd ..

    - name: Build website
      run: |
        cd www
          npm run build
        cd ..

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        name: "eggass"
        path: "www/dist/"
        retention-days: "1000"
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: "eggass"
